### ISSUE TITLE
Add body parsing.

### ISSUE THREAD

**Issue by brillout** [chriscalo/express-start#3]
What do you think of the following?

When

~~~js
const { start } = require("express-start");

const server = express();

start(server, {
  parseHttpBody: true,
});
~~~

then `express-start` adds the `express.json()` middleware.

Other sensible defaults like this could be added in the future.

**Comment by chriscalo** [comment]
I think I'd like to avoid this.

I'd prefer `express-start` to have exactly one purpose: a simpler way of starting an express app. I don't want it to modify how the express app works or bake in any default behavior.

Though that seems like something another utility library could accomplish:

``` js
const express = require("express");
const { start } = require("express-start");
const boilerplate = require("my-express-boilerplate");

const server = express();

server.use(boilerplate({
  parseHttpBody: true,
}));

// add more behavior to express app

start(server);
```

Seem reasonable?
